apiVersion: v1
kind: Service
metadata:
  name: composepost
  labels:
    app: composepost
spec:
  selector:
    app: composepost
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  type: LoadBalancer
  