apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - frontend-redis
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: frontend
        image: tgiannoukos/redis-test-go:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        command: ["/bin/frontend"]
        env:
        - name: SERVICE_NAME
          value: "frontend"
        - name: REDIS_ADDR
          value: "frontend-redis:6379"
        - name: GRPC_PORT
          value: "50051"
        - name: USER_SERVICE_ADDR
          value: "user-service:50051"
        - name: SEARCH_SERVICE_ADDR
          value: "search-service:50051"
        - name: RESERVATION_SERVICE_ADDR
          value: "reservation-service:50051"
        - name: RATE_SERVICE_ADDR
          value: "rate-service:50051"
        - name: PROFILE_SERVICE_ADDR
          value: "profile-service:50051"
