apiVersion: v1
kind: Service
metadata:
  name: poststorage
  labels:
    app: poststorage
spec:
  selector:
    app: poststorage
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  type: LoadBalancer
  