apiVersion: v1
kind: Service
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  selector:
    app: reservation
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  type: LoadBalancer
