apiVersion: v1
kind: Service
metadata:
  name: socialgraph
  labels:
    app: socialgraph
spec:
  selector:
    app: socialgraph
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  type: LoadBalancer
  