apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: tgiannoukos/redis-test-go:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        command: ["/bin/user -debug"]
        env:
        - name: SERVICE_NAME
          value: "user"
        - name: REDIS_ADDR
          value: "user-redis:6379"
        - name: GRPC_PORT
          value: "50051"
        - name: USER_SERVICE_ADDR
          value: "user-service:50051"
        - name: SEARCH_SERVICE_ADDR
          value: "search-service:50051"
        - name: RESERVATION_SERVICE_ADDR
          value: "reservation-service:50051"
        - name: RATE_SERVICE_ADDR
          value: "rate-service:50051"
        - name: PROFILE_SERVICE_ADDR
          value: "profile-service:50051"
