apiVersion: v1
kind: Service
metadata:
  name: {service_name}-redis
  labels:
    app: {service_name}-redis
spec:
  selector:
    app: {service_name}-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
