apiVersion: v1
kind: Service
metadata:
  name: {service_name}
  labels:
    app: {service_name}
spec:
  selector:
    app: {service_name}
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  type: LoadBalancer
