apiVersion: v1
kind: Service
metadata:
  name: {service_name}
  labels:
    app: {service_name}
spec:
  selector:
    app: {service_name}
  ports:
  - name: http  # Name for the first port
    protocol: TCP
    port: 50051
    targetPort: 50051
  {additional_port}  # Placeholder for additional port if needed
  type: LoadBalancer
  {external_ip}